"""empty message

Revision ID: 17d11603bd73
Revises: c0e8a94dc4cf
Create Date: 2020-06-28 19:37:54.657551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d11603bd73'
down_revision = 'c0e8a94dc4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayers', sa.Column('inviter', sa.String(), nullable=True))
    op.drop_constraint('prayers_inviter_id_fkey', 'prayers', type_='foreignkey')
    op.create_foreign_key(None, 'prayers', 'users', ['inviter'], ['id'])
    op.drop_column('prayers', 'inviter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayers', sa.Column('inviter_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prayers', type_='foreignkey')
    op.create_foreign_key('prayers_inviter_id_fkey', 'prayers', 'users', ['inviter_id'], ['id'])
    op.drop_column('prayers', 'inviter')
    # ### end Alembic commands ###
