"""empty message

Revision ID: 5a0db9fe88e1
Revises: bab280519857
Create Date: 2020-06-11 14:24:53.948297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0db9fe88e1'
down_revision = 'bab280519857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'participations', ['id'])
    op.add_column('prayers', sa.Column('same_gender', sa.Boolean(), nullable=True))
    op.drop_index('idx_prayers_location', table_name='prayers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_prayers_location', 'prayers', ['location'], unique=False)
    op.drop_column('prayers', 'same_gender')
    op.drop_constraint(None, 'participations', type_='unique')
    # ### end Alembic commands ###
