"""empty message

Revision ID: e7e582568c72
Revises: 5a0db9fe88e1
Create Date: 2020-06-11 15:41:26.593048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e582568c72'
down_revision = '5a0db9fe88e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayers', sa.Column('participant_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prayers', 'participant_count')
    # ### end Alembic commands ###
